export const ADD_TODO = "ADD_TODO";
export const REMOVE_TODO = "REMOVE_TODO";
export const TOGGLE_TODO = "TOGGLE_TODO";
export const MARK_COMPLETE = "MARK_COMPLETE";

export const ADD_TODO_LOADING = "ADD_TODO_LOADING";
export const ADD_TODO_SUCCESS = "ADD_TODO_SUCCESS";
export const ADD_TODO_ERROR = "ADD_TODO_ERROR";

export const GET_TODO_LOADING = "ADD_TODO_LOADING";
export const GET_TODO_SUCCESS = "GET_TODO_LOADING";
export const GET_TODO_ERROR = "GET_TODO_ERROR";
