export const ADD_TODO = "ADD_TODO";
export const MARK_COMPLETE = "MARK_COMPLETE";
export const DELETE_ONGOING = "DELETE_ONGOING";
export const DELETE_COMPLETED = "DELETE_COMPLETED";
export const DELETE_ALL_COMPLETED = "DELETE_ALL_COMPLETED";
export const MARK_INCOMPLETE = "MARK_INCOMPLETE";
